### ISSUE TITLE
Manejo de Carpetas Vacías

### ISSUE THREAD

**Issue by werfenGranate45** [Wmosaic/tilinos-pitos-finos#11]
Hay un tema a manejar sobre el CapDir(), en caso de que el usuario capture una ruta que adentro no tenga coincidencias con su extensión, que este vacío el Directorio o por otro caso haya archivos o subcarpetas que no se pueden abrir.

He aquí las posibles soluciones: 
- Para directorios de contenido vacío, verificamos la longitud de la lista, vector o arreglo y si hay un cero pues interrumpidos el programa para que no siga ejecutando las instrucciones que a su vez da solución por si no encuentra coincidencias con su extensión 

- También otro problema que pasa si no esta vacío el directorio y tiene subcarpetas o archivos de diferentes extensiones, además que requiere o quiere trabajar con distintos archivos entonces podemos hacer un filtro adentro del capFile() usando el método is_open() en caso de que sea True lo agrega a la lista, Vector, o arreglo, de lo contrario pasa.

- Quizá aquí se puede hacer uso de un método llamado areFiles() dentro de la clase Validadores para que se encargue de validar las subcarpetas y/o archivos dentro del directorio 

Nota: Detalle a contemplar es acerca de los parámetro de la extensión e incluirCarpeta, es que por omisión indicamos al programa que solo trabaja con una extensión (en este caso CSV), quizá se deba actualizar para que el usuario decida como quiere trabajar sus archivos, pidiéndole el dato de la extensión o el de IncluirCarpeta, sin embargo, nuestros dóminos del programa solo requerimos y trabajamos con CSV

**Comment by Wmosaic** [comment]
Desarrolla la idea del método `areFiles()` porque me parece similar a la funcionalidad que emplea [este](https://en.cppreference.com/w/cpp/filesystem/is_regular_file) método de biblioteca preexistente en c++, y que probablemente tiene presencia en los otros dos lenguajes.
Estoy abierto a la idea, pero necesitamos concretar el funcionamiento del método y si es realmente necesario o se pueden emplear metodos preexistentes.
