### ISSUE TITLE
Modularizar clases validador.

### ISSUE THREAD

**Issue by Wmosaic** [Wmosaic/tilinos-pitos-finos#4]
Modularizar las clases validador para mejorar la modularidad por medio de un sistema de herencia
Detalles de la herencia en discord, actualizaremos los algoritmos de validadores en la rama nueva donde se va a empezar a desarrollar el sistema de herencia.

**Comment by Wmosaic** [comment]
UPDATE -- NO SE EMPLEARA HERENCIA EN LOS VALIDADORES
El diseño de los validadores será concretado a la brevedad.
Sin embargo, si que se van a modularizar en <clases separadas> 
Por el momento, ignorar las indicaciones dadas, esperar al diseño de las clases.

**Comment by werfenGranate45** [comment]
[ACTUALIZACIÓN] LA CLASE MISELANIA SE CONVERTIRA EN LA DE MANEJO DE ARCHIVOS
